export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED"
} as const;
